var categoryData = {
  "categoryList": [
    {"category": "Smile", "categoryNo": "1.1"},
    {"category": "Bow15", "categoryNo": "2.1"},
    {"category": "Bow30", "categoryNo": "2.2"},
    {"category": "Bow45", "categoryNo": "2.3"},
    {"category": "Welcome", "categoryNo": "3.1"},
    {"category": "To put", "categoryNo": "4.1"},
    {"category": "Slip", "categoryNo": "4.2"},
    {"category": "Fasten", "categoryNo": "4.3"},
    {"category": "Fasten", "categoryNo": "4.4"},
    {"category": "Pull", "categoryNo": "4.5"},
    {"category": "Inflation", "categoryNo": "4.6"},
    {"category": "Pull", "categoryNo": "4.7"},
    {"category": "Blow", "categoryNo": "4.8"},
    {"category": "Located", "categoryNo": "5.1"},
    {"category": "Drop", "categoryNo": "5.2"},
    {"category": "Pull", "categoryNo": "5.3"},
    {"category": "Over", "categoryNo": "5.4"},
    {"category": "Slip", "categoryNo": "5.5"},
    {"category": "Seatbelt", "categoryNo": "6.1"},
    {"category": "Insert", "categoryNo": "6.2"},
    {"category": "Tightly", "categoryNo": "6.3"},
    {"category": "To unfasten", "categoryNo": "6.4"},
    {"category": "Lift", "categoryNo": "6.5"},
    {"category": "Front", "categoryNo": "7.1"},
    {"category": "Middle", "categoryNo": "7.2"},
    {"category": "Rear", "categoryNo": "7.3"},
    {"category": "Light", "categoryNo": "7.4"},
    {"category": "For", "categoryNo": "7.5"},
    {"category": "Thank you", "categoryNo": "8.1"}
  ]
};
